<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" style="background:none;">
<head>  
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="description" content="Xerces-Max" />
    <meta name="keywords" content="fitness sprave, teretana, aerobic, oprema"/>
    <meta name="author" content="www.ivan-golovic.from.hr" />
    <title>Xerces-Max</title>
    <link rel="stylesheet" type="text/css" href="/xerces-max.css" />
    <link rel="shortcut icon" href="/documents/xerces-max.ico" />
    <script type="text/javascript">
	window.onload = function() {
	    window.print();
	}
    </script>
</head>
<body style="background:none;">

<p style="font-weight:bold; padding:5px; text-align:left; border-bottom:1px silver solid;">
Xerces-Max
</p>

<?php echo $this->layout()->content ?>

<p style="font-weight:bold; padding:5px; text-align:right; border-top:1px silver solid;">
Xerces-Max
</p>

</body>
</html>
