<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>  
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="author" content="www.ivan-golovic.from.hr" />
    <title>Administracija</title>
    <link rel="stylesheet" type="text/css" href="/tooltip.css" />
    <link rel="stylesheet" type="text/css" href="/lcm.css" />
    <link rel="stylesheet" type="text/css" href="/highslide/highslide.css" />
    <link rel="shortcut icon" href="/images/lcm.png" />
    <!--[if lt IE 7]>
    <link rel="stylesheet" type="text/css" href="/highslide/highslide-ie6.css" />
    <![endif]-->
    <script type="text/javascript" src="/lcm.js"></script>
    <script type="text/javascript" src="/highslide/highslide-full.packed.js"></script>
    <script type="text/javascript" src="/highslide/highslide-conf.js"></script>
    <script type="text/javascript" src="/jquery-1.4.2.min.js"></script>
<script type="text/javascript" src="/tiny_mce/tiny_mce.js"></script>
<script type="text/javascript">
tinyMCE.init({
// General options
mode : "textareas",
theme : "advanced",
plugins : "safari,spellchecker,pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template,imagemanager,filemanager",
// Theme options
theme_advanced_buttons1 : "save,newdocument,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,|,styleselect,formatselect,fontselect,fontsizeselect",
theme_advanced_buttons2 : "cut,copy,paste,pastetext,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,|,insertdate,inserttime,preview,|,forecolor,backcolor",
theme_advanced_buttons3 : "tablecontrols,|,hr,removeformat,visualaid,|,sub,sup,|,charmap,emotions,iespell,media,advhr,|,print,|,ltr,rtl,|,fullscreen",
theme_advanced_toolbar_location : "top",
theme_advanced_toolbar_align : "left",
theme_advanced_statusbar_location : "bottom",
theme_advanced_resizing : true,
height : "400",
});
</script>
</head>
<body>
    <table class="mainAdminContainer">
	<tr>
	    <td>
		<div style="border:1px silver solid; padding:5px; margin:3px 3px 0px 3px;">
		    <div class="title">
			<span style="color:#777777; font-style:italic;">Lightweight Content Management</span>
		    </div>
		    <br />
		    <table cellpadding="0" cellspacing="0" style="width:100%;">
			<tr>
			    <td style="width:50%;">
				<div style="height:20px;" text-align:right;>
				    <ul class="horizontal">
					<li>
					    <a href="/lcm-admin-article-group">Grupe članaka</a> &nbsp;|&nbsp;&nbsp;
					</li>
					<li>
					    <a href="/lcm-admin-article">Članci</a> &nbsp;|&nbsp;&nbsp;
					</li>
					<li>
					    <a href="/lcm-admin-product-group">Grupe proizvoda</a> &nbsp;|&nbsp;&nbsp;
					</li>
					<li>
					    <a href="/lcm-admin-product">Proizvodi</a> &nbsp;|&nbsp;&nbsp;
					</li>
					<li>
					    <a href="/lcm-admin-order">Narudžbe</a>
					</li>
				    </ul>
				</div>
			    </td>
			    <td style="width:50%; text-align:right;">
	                <a title="Odjava iz sustava" href="lcm-admin-logout">Odjava</a> &nbsp;|&nbsp;&nbsp;
					<a title="Ovdje možete poslati e-mail s opisom problema" href="mailto:igolovic@gmail.com">Pomoć i podrška</a>				
			    </td>			    
			</tr>
		    </table>
		</div>
	    </td>
	</tr>
	<tr>
	    <td style="padding-top:0px;">
		<?php echo $this->layout()->content ?>
	    </td>
	</tr>
    </table>
</body>
</html>