<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" style="background:none;">
    <head>  
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <link rel="stylesheet" type="text/css" href="/xerces-max.css" />
    </head>
    <body style="background:none;">    
        <div class="contentWrapper">
            <form action="/lcm-sendlink/link=<?php echo $this->escape($this->link) ?>" method="post">
                <p>
                    <strong>1. Link koji šaljete</strong>
                </p>
                <p>
                    <?php echo $this->escape($this->link) ?>
                    <input type="hidden" name="sentLink" value="<?php echo $this->escape($this->link) ?>" />
                </p>
                <p>
                    <strong>2. Sigurnosna provjera</strong>
                </p>
                <p>
                    Upišite tekst sa donje slike u polje ispod slike.
                </p>
                <p style="text-align:center;">
                    <?php echo $this->captchaImage ?>
                </p>
                <p>
                    Tekst sa slike: <input style="float:right;" type="text" name="captcha[input]" maxlength="20" /> 
                </p>
                <p>
                    <strong>3. Unesite Vaše ime</strong>
                </p>
                <p>
                    Vaše ime: <input style="float:right;" type="text" name="senderName" maxlength="20" /> 
                </p>
                <p>
                    <strong>4. E-mail adresa primatelja</strong>
                </p>
                <p>
                    Adresa: <input style="float:right;" type="text" name="recipientAddress" maxlength="40" /> 
                </p>
                <p>
                    <input type="submit" value="Pošalji" />
                </p>
                
                <div class="error">
                    <?php if($this->senderNameError): ?>
                        Niste unijeli Vaše ime.
                    <?php endif ?>
                </div>
                <div class="error">
                    <?php if($this->recipientAddressError): ?>
                        Niste unijeli adresu primatelja.
                    <?php endif ?>
                </div>
                <div class="error">
                    <?php if($this->captchaError): ?>
                        Unijeli ste krivi tekst, pokušajte ponovno.
                    <?php endif ?>
                </div>
                <div class="error">
                    <?php if($this->sendMailError): ?>
                        Greška prilikom slanja e-mail poruke.
                    <?php endif ?>
                </div>
                <div class="ok">
                    <?php if($this->ok): ?>
                        Poruka je uspješno poslana.
                    <?php endif ?>
                </div>
                <input type="hidden" name="captcha[id]" value="<?php echo $this->escape($this->captchaMD5) ?>" />
            </form>
        </div>
    </body>
</html>